accessControl:
  salt: u0L7TKJPlD5h1mMumsDVxrdvSlT85U4S
api:
  key: D05E9307A8034C3191ED93D3EBBA72DB
controls:
- name: Actions
  type: section
  children:
  - command: M80
    name: Power On
    type: command
  - command: M81
    name: Power Off
    type: command
- name: Testing
  type: section
  children:
  - command: M119
    name: Endstops
    type: command
  - command: M119
    name: X
    type: feedback_command
    regex: "x_min: (.*)"
    template: "{0}"
  - command: M119
    name: Y
    type: feedback_command
    regex: "y_min: (.*)"
    template: "{0}"
  - command: M119
    name: Z
    type: feedback_command
    regex: "z_min: (.*)"
    template: "{0}"
events:
  enabled: true
  subscriptions:
  - command:
    - M80
    event: PrintStarted
    type: gcode
  - command:
    - M81
    - M117 Print Done %(now)s
    event: PrintDone
    type: gcode
  - command:
    - G28 X
    event: PrintCancelled
    type: gcode
plugins:
  discovery:
    upnpUuid: 0cb62ad0-b447-4fba-8a8e-5ade16c9536d
  softwareupdate:
    _config_version: 2
printerParameters: {}
printerProfiles:
  defaultProfile:
    axes:
      e: {}
      x: {}
      y: {}
      z:
        speed: 100
serial:
  baudrate: 250000
  port: /dev/ttyACM0
  timeout: {}
server:
  firstRun: false
  secretKey: Nq3WwCB6AVu5KtkT3rQVdrixhIU6o6xu
