#!/bin/sh

### BEGIN INIT INFO
# Provides:	  octocontroller
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the octocontroller service
# Description:       starts octocontroller using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC=octocontroller
NAME=octocontroller

octocontroller=/home/matt/work/3d-printer/octocontroller/controller.py
pidfile=/var/run/octocontroller.lock
logfile=/var/log/octocontroller.log


. /lib/lsb/init-functions

start() {
    start-stop-daemon --start --pidfile "$pidfile" --oknodo --quiet \
        --startas "$octocontroller" -- --background --pidfile "$pidfile" --log "$logfile"
}

stop() {
    start-stop-daemon --stop --pidfile $pidfile --oknodo
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
        start
		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
        stop
		log_end_msg $?
		;;

	restart)
		log_daemon_msg "Restarting $DESC" "$NAME"
		stop
		sleep 1
		start
		log_end_msg $?
		;;

	status)
		status_of_proc -p $pidfile "" $NAME
		;;

	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0
