accessControl:
  salt: mOY2vrOMolEZJ7lH2hxpE4qsXw8W02kv
api:
  key: CBB923E212D24AE9B494EDC2E3A5361C
appearance: {}
cura:
  config: /home/matt/work/models/slic3r.ini
  enabled: true
  path: /home/matt/.octoprint/bin/octoprint-slicer.sh
feature: {}
gcodeViewer: {}
printerParameters:
  movementSpeed:
    z: 100
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/ttyACM0
  timeout: {}
server:
  firstRun: false
  secretKey: DKq3mrjRiOouS06LEpwgcLLZXgWaC0W9
system: {}
temperature: {}
webcam: {}
