accessControl:
  salt: u0L7TKJPlD5h1mMumsDVxrdvSlT85U4S
api:
  key: D05E9307A8034C3191ED93D3EBBA72DB
appearance: {}
cura:
  config: /home/matt/work/models/slic3r.ini
  enabled: true
  path: /opt/OctoPrint/.octoprint/bin/slicer.sh
feature: {}
gcodeViewer: {}
printerParameters:
  movementSpeed:
    z: 100
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/ttyACM0
  timeout: {}
server:
  firstRun: false
  secretKey: DKq3mrjRiOouS06LEpwgcLLZXgWaC0W9
  secretKey: Nq3WwCB6AVu5KtkT3rQVdrixhIU6o6xu
system: {}
temperature: {}
webcam: {}
controls:
  - name: PSU
    type: section
    children:
      - name: Power On
        type: command
        command: M80
      - name: Power Off
        type: command
        command: M81
